plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '6.0.54'
}

version = mod_version
group = 'com.valorcraft.economy'

base {
    archivesName = 'AurumCore-1.20.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
}

minecraft {
    mappings channel: 'official', version: "${minecraft_version}"

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            mods {
                economy_core {
                    source sourceSets.main
                }
            }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            mods {
                economy_core {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
    manifest {
        attributes([
                'Specification-Title'   : 'AurumCore',
                'Specification-Version' : project.version,
                'Specification-Vendor'  : 'ValorCraft',
                'Implementation-Title'  : 'AurumCore',
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor': 'ValorCraft'
        ])
    }
}
