modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="economy_core"
version="${version}"
displayName="VEconomy"
authors="ValorCraft"
displayTest="IGNORE_SERVER_VERSION"
description='''Серверное ядро цифровой экономики ValorCraft (Forge 1.20.1): личный баланс игроков по UUID (long, минимальные единицы), атомарные переводы, журнал операций и безопасный Java API. Данные — SQLite (WAL) или MySQL (пул HikariCP). Работает без клиентской части; клиенту мод не требуется.'''

[[dependencies.economy_core]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.economy_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="SERVER"
